language: node_js
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libnss3
  chrome: stable

node_js:
  - "8"
script:
  - npm test
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls