language: node_js
dist: trusty
sudo: required
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  chrome: stable

node_js:
  - "8"
script:
  - npm test
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls