const FAVORITE_SET_REQUEST = 'FAVORITE_SET_REQUEST'
const FAVORITE_SET_SUCCESS = 'FAVORITE_SET_SUCCESS'
const FAVORITE_LIST_REQUEST = 'FAVORITE_LIST_REQUEST'
const FAVORITE_LIST_SUCCESS = 'FAVORITE_LIST_SUCCESS'

export default {
  FAVORITE_SET_REQUEST,
  FAVORITE_SET_SUCCESS,
  FAVORITE_LIST_REQUEST,
  FAVORITE_LIST_SUCCESS,
}
