const LOADING_HOME_NOTIFICATION = 'LOADING_HOME_NOTIFICATION'
const LOADING_DETAILS_PAGE_NOTIFICATION = 'LOADING_DETAILS_PAGE_NOTIFICATION'

export default {
  LOADING_HOME_NOTIFICATION,
  LOADING_DETAILS_PAGE_NOTIFICATION,
}
