export const LOADING_DETAILS_PAGE_NOTIFICATION = 'LOADING_DETAILS_PAGE_NOTIFICATION'
export const LOADING_DETAILS_INTERNAL_NOTIFICATION = 'LOADING_DETAILS_INTERNAL_NOTIFICATION'
export const LOADING_HOME_NOTIFICATION = 'LOADING_HOME_NOTIFICATION'

export default {
  LOADING_DETAILS_PAGE_NOTIFICATION,
  LOADING_DETAILS_INTERNAL_NOTIFICATION,
  LOADING_HOME_NOTIFICATION,
}
