const REQUEST_CHARACTER_LIST = 'REQUEST_CHARACTER_LIST'
const SUCCESS_CHARACTER_LIST = 'SUCCESS_CHARACTER_LIST'

const REQUEST_CHARACTER_ITEM = 'REQUEST_CHARACTER_ITEM'
const SUCCESS_CHARACTER_ITEM = 'SUCCESS_CHARACTER_ITEM'

const REQUEST_CHARACTER_DETAIL = 'REQUEST_CHARACTER_DETAIL'
const SUCCESS_CHARACTER_DETAIL = 'SUCCESS_CHARACTER_DETAIL'


export default {
  REQUEST_CHARACTER_LIST,
  SUCCESS_CHARACTER_LIST,

  REQUEST_CHARACTER_ITEM,
  SUCCESS_CHARACTER_ITEM,

  REQUEST_CHARACTER_DETAIL,
  SUCCESS_CHARACTER_DETAIL,
}
